# Generated by Django 5.1.4 on 2024-12-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_worker_information_worker_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="profile_picture",
            field=models.ImageField(
                default="default/profile_picture.jpg", upload_to="profile_pictures/"
            ),
        ),
    ]
