# Generated by Django 5.1.4 on 2024-12-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_alter_worker_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/default.jpg", upload_to="profile_pictures/"
            ),
        ),
    ]
