# Generated by Django 5.1.4 on 2025-01-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_worker_hire_date_worker_last_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="hire_date",
        ),
    ]
