# Generated by Django 5.1.4 on 2025-01-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0008_remove_worker_hire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
