# Generated by Django 5.1.4 on 2025-01-04 15:19

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_worker_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/default.jpg",
                upload_to=manager.models.unique_file_path,
            ),
        ),
    ]
