# Generated by Django 5.1.4 on 2025-01-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0010_alter_worker_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="facebook",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="instagram",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="twitter",
            field=models.URLField(blank=True),
        ),
    ]
