# Generated by Django 5.1.4 on 2025-01-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0011_worker_facebook_worker_instagram_worker_twitter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worker",
            old_name="information",
            new_name="description",
        ),
    ]
