# Generated by Django 5.1.4 on 2025-01-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0012_rename_information_worker_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
