# Generated by Django 5.1.4 on 2025-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0014_alter_project_team_alter_worker_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
    ]
