# Generated by Django 5.1.4 on 2025-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0016_remove_team_workers_team_leader_worker_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
